# FILL OUT THIS WITH YOUR KEYS AND RENAME TO keys.py

OPENAI_KEY=
CLAUDE_KEY=
GOOGLE_API_KEY=
GEMINI_API_KEY=
GOOGLE_SEARCH_ENGINE_ID = 
GROK_API_KEY =
DEEPSEEK_API_KEY = 
REDDIT_CLIENT_ID = 
REDDIT_SECRET = 
REDDIT_USER_AGENT = 
